### ISSUE TITLE
Don't collapse expanded tree in the UI when clearing the search field

### ISSUE THREAD

**Issue by Javaru** [alex-yh99/AwesomeKotlinPlugin#1]
Currently when you clear the search box (via the `x` icon), the UI (i.e. the expanded tree view) is reset. This prevents the following use case:

I know about library "foo" and I want to see what similar/alternative libraries there might be, and perhaps I'm not sure what category it might be under. So I search for 'foo' and see it in the tree under _Libraries/Frameworks > Subcategory_. Now to see what else is in that subcategory I'd like to select "Subcategory" in the tree and clear the search so the other items are shown.

But when I do that, the UI is reset and the expanded tree is collapsed. So I now have to navigate back to the expanded node. It makes sense that as I type (either forward or backspacing), the search is done and the UI is updated with the new results. But if I clear the search string, the search results need to be reset (i.e. everything is shown), but the expanded tree should not be reset.  This is the behavior in most searches I have seen. Alternatively, if a node in the tree has been selected, then upon clearing the search box, the expanded tree should not be reset.

p.s. thanks for a very useful plugin.

**Comment by yaohui-wyh** [comment]
@Javaru the search box works in similar way to the _Search Anywhere_ popup which updates results as you type.

I tried keeping the tree selection path, however it does work as expected. Please take a look at [#1d65a7a](https://github.com/alex-yh99/AwesomeKotlinPlugin/commit/1d65a7a63992e95b272c627db621c33f9975c8c1) if you are interested in implementing the feature.
