### ISSUE TITLE
Support for idea 2022.1.4

### ISSUE THREAD

**Issue by icypig** [alex-yh99/AwesomeKotlinPlugin#2]
For currently only compatible with 2022.1.3, can't use in 2022.1.4 😭

**Comment by yaohui-wyh** [comment]
Thanks @icypig, v1.2.0 is available at https://github.com/yaohui-wyh/AwesomeKotlinPlugin/releases/tag/v1.2.0

You can also wait for plugin update to be approved by the JetBrains Marketplace:
https://plugins.jetbrains.com/plugin/11357-awesome-kotlin/versions
